---
driver:
  name: vagrant
  customize:
    memory: 2048
    cpus: 2

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  retry_on_exit_code:
  - 35 # 35 is the exit code signaling that the node is rebooting
  max_retries: 1
  client_rb:
    exit_status: :enabled # Opt-in to the standardized exit codes
    client_fork: false  # Forked instances don't return the real exit code
    environment: _default
  product_name: chef
  product_version: 15
  chef_license: accept

verifier:
  name: inspec

platforms:
  - name: harbour
    attributes:
      chef_software:
        chef_server_api_fqdn: chef-server.test
        chef_automate_api_fqdn: chef-automate.test
        chef_supermarket_api_fqdn: chef-supermarket.test
        automate_admin_token: nil
        automate_IAM_version: v2
        adm_password: iamtheboss
        a2_version: latest # 20190513175357

suites:
  - name: a2
    driver:
      box: bento/centos-7
      vm_hostname: chef-automate.test
      synced_folders:
      - [".", "/opt/support", create: true, owner: "root", group: "root"]
      network:
      - ["private_network", {ip: "192.168.33.199"}]
      customize:
        memory: 3072
    run_list:
      - recipe[chef_software::chef_automatev2]
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/automatev2
    attributes:
    lifecycle:
      post_converge:
      - local: |
          knife ssl fetch https://chef-automate.test
          cp /Users/clavery/.chef/trusted_certs/chef-automate_test.crt ./certs
      - remote: |
          if [ ! -f /opt/support/files/admin_token.yml ]; then
            TOK="$(sudo chef-automate iam token create support --admin)"
            sudo echo "admin_token: ${TOK}" > /opt/support/files/admin_token.yml
            fi
            sudo hab pkg install chef/gatherlogs_reporter -b --force
      post_verify:
      - remote: |
          export HOST=$(uname -n)
          sudo chef-automate gather-logs -o /opt/support/logs/newlogs/$HOST.tar.gz
          gatherlog report automate2 -p /opt/support/logs/newlogs/$HOST.tar.gz
          mv /opt/support/logs/newlogs/$HOST.tar.gz /opt/support/logs/oldlogs/$HOST-`date +%Y%m%d%H%M%S`.tar.gz

      pre_destroy: 
      - local: |
          rm -f  files/admin_token.yml certs/chef-automate_test.crt

      - remote: |
          export HOST=$(uname -n)
          rm -rf l/opt/support/ogs/{new,old}logs/$HOST* 
        skippable: true

  - name: server
    driver:
      box: bento/centos-7
      vm_hostname: chef-server.test
      synced_folders:
      - [".", "/opt/support", create: true, owner: "root", group: "root"]
      network:
      - ["private_network", {ip: "192.168.33.200"}]
    run_list:
      - recipe[chef_software::chef_server]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
    lifecycle:
      post_converge:
      - local: |
          knife ssl fetch https://chef-server.test
          cp /Users/clavery/.chef/trusted_certs/chef-server_test.crt ./certs
      - remote: |
          sudo chef-server-ctl set-secret data_collector token <%= if File.exist?('files/admin_token.yml')
                                                                '"' + YAML::load_file('files/admin_token.yml')['admin_token'] + '"'
                                                                else 
                                                                '"INVALID"' 
                                                                end %>
          sudo chef-server-ctl restart nginx
          sudo chef-server-ctl restart opscode-erchef
          sudo mkdir -p /hab/accepted-licenses
          sudo touch /hab/accepted-licenses/habitat
          sudo curl https://raw.githubusercontent.com/habitat-sh/habitat/master/components/hab/install.sh | sudo bash
          sudo hab pkg install chef/gatherlogs_reporter -b --force
      post_verify:
      - remote: |
          export HOST=$(uname -n)
          sudo chef-server-ctl gather-logs && mv $HOST* /opt/support/logs/newlogs/
          gatherlog report chef-server -p /opt/support/logs/newlogs/$HOST* 
          mv /opt/support/logs/newlogs/$HOST* /opt/support/logs/oldlogs/

      pre_destroy: 
      - local:
          rm -f certs/chef-server_test.crt
      - remote: |
          export HOST=$(uname -n)
          rm -rf /opt/support/logs/{new,old}logs/$HOST* 
        skippable: true 

  - name: sprmkt

    driver:
      box: bento/centos-7
      customize:
        memory: 1024
        cpus: 1
      vm_hostname: chef-supermarket.test
      synced_folders:
      - [".", "/opt/support", create: true, owner: "root", group: "root"]
      network:
      - ["private_network", {ip: "192.168.33.201"}]
    run_list:
      - recipe[chef_software::chef_supermarket]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:

  - name: cl-1
    driver:
      box: bento/centos-7
      vm_hostname: client-1.test
      customize:
        memory: 512
      synced_folders:
      - [".", "/opt/support", create: true, owner: "root", group: "root"]
      network:
      - ["private_network", {ip: "192.168.33.202"}]
    provisioner:
      name: chef_solo
      always_update_cookbooks: true
      retry_on_exit_code:
      - 35 # 35 is the exit code signaling that the node is rebooting
      max_retries: 1
      install_strategy: always # in case a new a2 token is created we need to crossload into the node
      solo_rb:
        chef_server_url:  "https://chef-server.test:8989"
        log_location:   STDOUT
        node_name: "client-1.test"
        trusted_certs_dir: "/opt/support/certs"
        data_collector.server_url: "https://chef-automate.test/data-collector/v0"
        data_collector.mode:       :both
        data_collector.token:  <%= if File.exist?('files/admin_token.yml')
                                '"' + YAML::load_file('files/admin_token.yml')['admin_token'] + '"'
                                else 
                                '""' 
                                end %> 
      product_name: chef
      product_version: 15.2.20
      chef_license: accept
    lifecycle:
      pre_converge:
        - remote: |
            HC=$(cat /etc/hosts | wc -l ) 
            echo $HC
            if [ "$HC" == "3" ]; then 
              cat /opt/support/files/hosts.txt | sudo tee -a /etc/hosts
            fi

  - name: cl-2
    driver:
      box: bento/ubuntu-18.04
      vm_hostname: client-2.test
      customize:
        memory: 512
      synced_folders:
      - [".", "/opt/support", create: true, owner: "root", group: "root"]
      network:
      - ["private_network", {ip: "192.168.33.203"}]
    provisioner:
      name: chef_solo
      always_update_cookbooks: true
      retry_on_exit_code:
      - 35 # 35 is the exit code signaling that the node is rebooting
      max_retries: 1
      install_strategy: always # in case a new a2 token is created we need to crossload into the node
      solo_rb:
        chef_server_url:  "https://chef-server.test:8989"
        log_location:   STDOUT
        node_name: "client-2.test"
        trusted_certs_dir: "/opt/support/certs"
        data_collector.server_url: "https://chef-automate.test/data-collector/v0"
        data_collector.mode:       :both
        data_collector.token:  <%= if File.exist?('files/admin_token.yml')
                                '"' + YAML::load_file('files/admin_token.yml')['admin_token'] + '"'
                                else 
                                '""' 
                                end %> 
      product_name: chef
      product_version: 13.6
      chef_license: accept
    lifecycle:
      pre_converge:
        - remote: |
            HC=$(cat /etc/hosts | wc -l ) 
            echo $HC
            if [ "$HC" -lt "8" ]; then 
              cat /opt/support/files/hosts.txt | sudo tee -a /etc/hosts
            fi
